apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ibo30eub9-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ibo30eub9-dotnet-basic-gitops